### ISSUE TITLE
Etherscan links are broken

### ISSUE THREAD

**Issue by LorensHuculak** [Proof-Of-Humanity/proof-of-humanity-web#108]
**Describe the Bug**
The Etherscan links on profiles redirect the user to "https://mainnet.etherscan.io/" -which does not exist - instead of "https://etherscan.io".
**To Reproduce**
Click an ETH address on PoH Profiles
**Expected Behavior**

**Screenshots**

**Device and Browser Information**

**Comment by jragosa** [comment]
Fixed

**Comment by LorensHuculak** [comment]
Not fixed, https://mainnet.etherscan.io/address/0x23a22031484c7a2ae5dc0f8f48c17235a5dfa048

Still redirects to mainnet.etherscan, which doesn't exist.

**Comment by jragosa** [comment]
Regression, the incorrect links are indeed back.
